services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      ./prestashop_8.2.1:/app
      #vhost nginx
      #certificados
    networks:
      redelamplemp:
        aliases:
          - test.lan
  phpserver:
    build: php-lemp
    volumes:
      ./prestashop_8.2.1:/app
      #php.ini
    networks:
      redelamplemp:
  basededatos:
    image: mysql:latest
    environment:
      #Configuracion da BD de desenrolo
    volumes:
      - datos:/var/lib/mysql
    networks:
      redelamplemp:
  #phpmuadmin se se necesita
  cliente:
    hostname: cliente
    image: brunosct/debian12-cliente-firefox
    networks:
      - redelamplemp
    environment:
    - DISPLAY=${DISPLAY}
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix  
volumes:
  datos:
networks:
  redelamplemp: